apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devoxx-deployment
  labels:
    app: hello-devoxx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devoxx-app
  template:
    metadata:
      labels:
        app: hello-devoxx-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: hello-devoxx
        image: 836964591189.dkr.ecr.eu-west-3.amazonaws.com/devoxx:dynamodb-streams-3
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: "xray-service.default:2000"
          - name: AWS_XRAY_ENABLED
            value: "true"
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux