apiVersion: v1
kind: Service
metadata:
  name: hello-devoxx-service
  labels:
    app: hello-devoxx-app
spec:
  selector:
    app: hello-devoxx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80